language: cpp
matrix:
  include:
  - os: osx
    osx_image: xcode10
cache:
  directories:
  - "$HOME/Library/Caches/Homebrew"
before_install:
- git submodule update --init --recursive
install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./Build/Depends/prepare_macos.sh ; fi
before_script: 
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./Scripts/release_macos.sh ; fi
after_script: 
after_success: 
after_failure: 
deploy:
  provider: s3
  access_key_id: AKIAJI2NHFF6LNSLEEJA
  secret_access_key:
    secure: I8Fg9L1vAsmd1T0wEJx1WNqYgY3cnpIzJXQbg82Mt0jd+WgjhEGrNpYtE/HxI2G0dnabpyaZ4hiZDpbZTg14x6GwLiwlb5QJJEK/DB9Iu33mxl9zqaf95ZWXfhdOwC8nKZii1QJL2IZtp7sZoRMbkPCQkO31kq4tjPCqB31ga45ATxlOLqVd/Uw65FBxwk+YfhfMZgxk8CjMDA0kI90UXJQWWLGJKC9DKdcX6MyHDC5g1V3M/HpAHsRQCBlazSZ/pcSNmJsQVqr+qGDMTgUwg7gdvuLrZ+NuxXOx9hVEGbRIWh4culdwbCE6Df/8O4I115zBfwOPWfaHMnRWCweVJTkFqEk/6MDhNF2mt62oypFhZY398myxpRDAo6ifZHzxlju25q3tOVWumyBNkqmRZyrw1/7iH79Z0ulKFpqYaUuD+CjJQZvVf0CsngivWpx9WTtrvHU6zsCD34wxc+deHD6q77YxRWGXHWSsTfw6NumvJlqONk4IHT/0v1ULzZQvW4VdoRahdQChw+jjYG0JokxMziWoNg+CtVMPKNKBnjVysaM6BkZWpzUVTBEL60ph8lrbzAwLePUfT9ZieeoudGs+uf9luUaibC/tqthR6mSeraK90E+/Lk0r24q9cn+JIki5YdOrfEtjLIpU/fMRjE31x0NNKT4oSufRC6KUZ2k=
  bucket: spritestudio-public
  on:
    branch: master
  region: ap-northeast-1
  local_dir: Tools
  skip_cleanup: true
    repo: SpriteStudio/SpriteStudio6-SDK
