language: cpp
matrix:
  include:
  - os: osx
    osx_image: xcode10
cache:
  directories:
  - "$HOME/Library/Caches/Homebrew"
before_install:
	- git submodule update --init --recursive
install:
	- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./Build/Depends/prepare_macos.sh ; fi
before_script: 
script:
	- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./Scripts/release_macos.sh ; fi
after_script: 
after_success: 
after_failure: 
deploy:
  provider: s3
  access_key_id:
  	secure: "Kw+0rnD793H8rVc4TnqlrLxR1wDOk2WbFCnXiSDKDK5rdsqg0fodbKM2/dnNWn9tk39EF++lBp7NaFymcuMUPtVskKPObG9yC70Mepyrk8p2M85qkWRvDM2MVUaYyMdc/oxY1+LAzTOV37AIhyYO5ma/4zEdAUevwoFZEl6EA663QjFe81fcl96sPFo1P9Whaa4MOiLgerU52IH/vI1oiWiCYqZUfIPHtJePv1LQI4zkzBLTZO9NPV79ZFsuQdj/5iH8bz4zi71380FyGYjaBF4HTxAqHIUcXqKfriqBhdZBFn5rSN3bXZYKxmR7dbpcTx9DdFRHtzlfp4on7R2SF6ZSY4pEBfAFwVruSVG5vxtI74tuDCu8xOvAiN8TIVNXQUR6oSOCyAzIUY9mpgMusSr8cbTN40mhsOQ3DFADaLFU5X7IfI5p6frBntvsX/yPzxpjm53OwIxzbdL59y53oSYy+jb2Pe16NgNaZNwZvkuF+yQhujS0e+nArMWTjUo1+GuaNjtVta+AeXIxN6fQsjWXJUjJGVrvoHQkXoxs8PJkPFfW5fk7t9ezzGyIMZCvtp8MfgSEmVu7BSYJXhJAv/HZQOHaqZomn90gjZ0Y+0UpxFV9KjDmjIrwtrmBPJQSav6RRBrc9gfX3JkxZrw3yy+9kLDFfeQ4V3eFS74mcZE="
  secret_access_key:
	secure: "SN1PsHaoFTDNfRetSIoWPPdObrO1PNIk+LrMaW290vG4Kji/efrDGhPJTGU3lGAC6+T1RfLx8wQVFzVkl7Y4Xcmow+i/htxtrcNcPPksRV7Nhvz2bLO9tlka4/1nEtqW05qr6jqVEGNsAMz74cTmOY9x4DvNaHBjaB4JyV1uC2iCT+xrzlndxqwXIfqjIYFsK1Q9pe0knjJtAZ5CGew3LvqvnzVCU9X9XJ/gzFtM59KHIFB6WDyxm9lcLlUMfoC9cURwnkkfVzVQH0bdMJ9LR9ebtTHTZDWdMgjzHUiaj7W9rg2uPtQVtqNZ2laCSyl4Lx3ZZcypLSfoc/Wt0Uj+BjaBEowm3qhmNw2DxpKHSqzahx1ljCBTiEg0nC0wh+xgQXMiduE/i+DpTd6W2uSjY/wbPGN9i7ZgOZplK63o6VGsCR+cdbU0d1tXjNPChSWMgk1C27NRHX15UbHvGZCCjxpjJWvidDuKNIolngiRjGJuNdqEIeo+o5ZW9eT7taFPq08mbyWp+TfO1lCs6D/T/04qsvx8x6X01bVv2LwOX5e/zA7TxFiQXqCiFf630ykdFSz8vkzr6p2xawjIXqQxTOjJanKnetEIFlfnkNuWdQLHGs5T5ZjoPeExrp1IcpxzHVJuzRsshuPyvFnlB8GxJDxn+/ciR/mu9darqojfecU="
  bucket: spritestudio-public
  on:
    branch: master
  region: ap-northeast-1
  local_dir: Tools
  skip_cleanup: true
    repo: SpriteStudio/SpriteStudio6-SDK
