language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode10
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
before_install:

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew reinstall qt ; fi

before_script:
  - git submodule update --init --recursive

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./Scripts/release_macos.sh ; fi
 
after_script:

after_success:

after_failure:

deploy:
  provider: s3
  access_key_id: AKIAJI2NHFF6LNSLEEJA
  secret_access_key:
    secure: "XilovAQWcBUCz40wfKRnRQLQ3ZyKWtLDwK+hCDZ+3tj1gAuUY4Om7l52pUYUCsIPcW+Z2oAZBmAJwaSczkx6cXFjoDNzXGkzMr6t77P+MvlRPEm3O78SkzYNP1GYq1nAsdHU9jUXqwN/2e4nZJvjK/XQ9RNJRdsvaWP8G/AHwkzjuhZS7cbvUg9q3nPRFFI36AfPfARQqppqg5r00BLAMC5XnTXon1Yev5NDmSW46KCzoqG8Js5rKu0KTzubnwn2dwPFb+9naxNSwMLTfH6+W/5Z6TSfeSHhRLMl9FxAyr1nUZGqiiUUMxlXq6Jzs60eZiNY4qdLoAJ6U2MJ2L/Vzgw0DmCEp2Sa1mXbhWsT+Puawk9XMJh00xZSnvVLaKnje1tzsIrYQeygnzVJeqo9fVTgSI38MvtWiI4cgAWcubJ5ZQv3z0OWH8fswb6RPRfVfh7x+LvdqlxkvC2vVE9YpTBZmrN2V3jTe0D0HKT33cGbtBvuwlN97BV4GQhbc6eYE+8vBfx0+Ry3AHZCtYisDFLdcL1nsmSpsZ5kNaMZfBsUy+AZTV+0daPLp1fC1g7Qd2sMNTNDVPQHH+QxjaO9OrWwM8OGeBA4RLy4ZAFtttv1ZyjNxBMpGuMEaBvYBntKRUPsxw6TTNxB++oq1h8tbl7g3Gv47t2aN5WGsqS0F3Y="
  bucket: spritestudio-public
  on:
    branch: develop
    
