language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode10
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
before_install:

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew reinstall qt ; fi

before_script:
  - git submodule update --init --recursive

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./Scripts/release_macos.sh ; fi
 
after_script:

after_success:

after_failure:

deploy:
  provider: s3
  access_key_id: AKIAJI2NHFF6LNSLEEJA
  secret_access_key:
    secure: QGOO4lYwtdORc7zHjQAKvAuf0Pr8wqVMXMyLxdMVB8XRa4XrnrFyXOMsEt/KvTYZulg87o5+nx1+VSgYZxkDUPkyT49kLRaPzubp0BOZn8wCAhX0pQg68Ehev5/fqY4LctlfliKBg/yluYUzLuJAQiQKG8mIEV340BlZd1k2kYYaTJzTOTpD8MyFrqb76hpnEedTJxiWhwQuUWJT6x0CqnWFp0npe0SYF0VwqG5SLUaxe5oGs1sv1r7oidi2QlmMAMgKBWUtFy2AwALjP0jx0UIn1OA0pvhR0pxCNxXBMpmyjReAvnGAYl8nLnBszxyPvRACo+6C+tYlwkY9VWYLlmDKwDTV7Xv3NnnGsmfB2QwGIw7pvPdf8lvyyo9nCxrrSp9Vb38vIoVYPsMIb/yBE6vYF1Fa1WO3LWZRMk/JsbBmN10ImIo/ZUegy4V36oiqJ7+516pU9SS/fLcnwUG9k507GrK2a35cu20D4GBTg87d4XZxLYMIPHTp8ipBRMsOYyVIbANWkeyCouLMooS0pthmevix2BbT1PaTOE/WLcU6OpsuZtQfxqOpVDkHa3Mp7eQMozHA/6PDQkwRajBIFCx0OPzkePWkdsIksF7IBSlTZdJPOr2U5jhfNmL/Ghuju0KPIHAp5ix4ABGcP3OWb6o43U7VXOtab71pdg6apZY=
  bucket: spritestudio-public
  on:
    branch: develop
    
