name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: "update submodules"
      uses: "srt32/git-actions@v0.0.3"
      with:
        args: "git submodule update --init --recursive"
    - name: prepare build environment
      run: ./Build/Depends/prepare_macos.sh
    - name: release build
      run: ./Scripts/release_macos.sh
