name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: "git submodule"
      run: git submodule update --init --recursive
    - name: prepare build environment
      run: ./Build/Depends/prepare_macos.sh
    - name: release build
      run: ./Scripts/release_macos.sh
